### ISSUE TITLE
Add-on not working on startup

### ISSUE THREAD

**Issue by aguyfromsector2814** [glutanimate/colorful-tags#17]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Add-on failed upon start-up, tried deleting and redownloading, as well as the other items on the checklist below. I have pasted the debug info below as well.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-13 08:56:48

When loading Colorful Tags:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/594329229/__init__.py", line 22, in <module>
    from .sidebar import patch_sidebar
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/594329229/sidebar/__init__.py", line 26, in <module>
    from .menu import maybe_add_context_actions
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/594329229/sidebar/menu.py", line 25, in <module>
    from PyQt5.QtCore import QModelIndex
ModuleNotFoundError: No module named 'PyQt5'
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python



```

**Comment by AnKingMed** [comment]
@glutanimate do you have any idea what's going on here? I tried to troubleshoot. it's working fine for me

**Comment by glutanimate** [comment]
@AnKingMed same here


@aguyfromsector2814 it looks like you're using an older version of the add-on, although I'm not sure why it wasn't updated automatically by Anki. Please uninstall the version you currently have installed by going to Tools → Add-ons. Then please restart Anki and reinstall the add-on [from AnkiWeb](https://ankiweb.net/shared/info/594329229) (code: 594329229). If everything went well, the error message should no longer appear after restarting Anki.

**Comment by aguyfromsector2814** [comment]
That worked, thank you both for the help!
